In [2]:
import numpy as np

In [3]:
init_state = np.array([[0,0,0,0,0,0,0],
                      [0,0,0,0,0,0,0],
                      [0,0,0,0,0,0,0],
                      [0,0,0,0,0,0,0],
                      [0,0,0,0,-1,0,0],
                      [0,0,0,0,1,0,0]])



In [ ]:
init_state = np.array([[0,0,0,0,0,0,0],
                      [0,0,0,0,0,0,0],
                      [0,1,0,-1,-1,0,0],
                      [-1,0,-1,0,0,0,0],
                      [0,-1,0,1,-1,0,0],
                      [-1,0,0,0,1,0,0]])



def is_terminal_state( s : np.ndarray,player) -> tuple:
        
        rows, columns = s.shape
    
        # Verificar Horizontalidad
        for r in range(rows):
            for c in range(columns-3):
                if s[r,c] == player and s[r,c+1] == player and s[r,c+2] == player and s[r,c+3] == player:
                    return False,True
                
        # Verificar Verticalidad
        for c in range(columns):
            for r in range(rows-3):
                if s[r,c] == player and s[r+1,c] == player and s[r+2,c] == player and s[r+3,c] == player:
                    return (False,True)
                
        # Verificar Diagonales (Izquierda)
        for c in range(columns-3):
            for r in range(rows-3):
                if s[r,c] == player and s[r+1,c+1] == player and s[r+2,c+2] == player and s[r+3,c+3] == player:
                    return (False,True)
                
        # Verificar Diagonales (Derecha)
        for c in range(columns-3):
            for r in range(3,rows):
                if s[r,c] == player and s[r-1,c+1] == player and s[r-2,c+2] == player and s[r-3,c+3] == player:
                    return (False,True)

        if s[0,0] != 0 and s[0,1] != 0 and s[0,2] != 0 and s[0,3] != 0 and s[0,4] != 0 and s[0,5] != 0 and s[0,6] != 0:
            return (True,True)

        return False, False

is_terminal_state(init_state,-1)

(False, True)

In [ ]:
[[ 0  0  0  0 -1  0  0],
 [ 0  0  1 -1  1  0  0],
 [ 0  1 -1  1  1  0 -1],
 [ 0 -1  1  1 -1  1  1],
 [ 0 -1  1 -1  1 -1  1],
 [ 1 -1 -1  1 -1 -1 -1],]

[[ 0  0  0  0 -1  0  0]
[ 0  0  1 -1  1  0  0]
[ 0  1 -1  1  1  0 -1]
[ 0 -1  1  1 -1  1  1]
[ 0 -1  1 -1  1 -1  1]
[ 1 -1 -1  1 -1 -1 -1]]

SyntaxError: invalid syntax. Perhaps you forgot a comma? (1956695969.py, line 1)